version: '3.1'
services:
  stats-server:
    container_name: stats-server
    build:
      context: ./stats/stats-server
    ports:
      - "9090:9090"
      - "5005:5005"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
      - TZ=${TZ}

  stats-db:
    container_name: stats-db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
      - TZ=${TZ}
    volumes:
      - stats-db-data:/var/lib/postgresql/data

  ewm-service:
    container_name: ewm-service
    build:
      context: ./ewm-service
    ports:
      - "8080:8080"
      - "5006:5006"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:5006,server=y,suspend=n
      - TZ=${TZ}

  ewm-db:
    container_name: ewm-db
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
      - TZ=${TZ}
    volumes:
      - ewm-db-data:/var/lib/postgresql/data

volumes:
  stats-db-data:
  ewm-db-data:
